// This file has been generated by Specta. DO NOT EDIT.
// TEMPORARY PLACEHOLDER: Stage 0 Task 6 手工占位，Windows 首次 `cargo test specta_export`
// 后 tauri-specta 会重新覆盖此文件，届时所有类型以 Rust struct 为准。

export type SessionSummary = {
  session_id: string;
  project_name: string;
  cwd: string;
  phase: string;
  needs_attention: boolean;
  last_message: string | null;
  tool_name: string | null;
  tool_input: Record<string, unknown> | null;
};
